"use client";

import React, { useState, useMemo } from 'react';
import {
  useGetSaleReturnsQuery,
  useGetSaleReturnStatsQuery,
  useUpdateReturnStatusMutation,
  useDeleteSaleReturnMutation,
  useCreateSaleReturnMutation,
  ReturnStatus,
  CreateSaleReturnRequest,
} from '@/state/saleReturnsApi';
import { useGetSalesQuery } from '@/state/salesApi';
import { useAppSelector, useAppDispatch } from '@/app/redux';
import { 
  setCurrentPage, 
  setStatusFilter, 
  setShowCreateModal, 
  setSelectedReturnId 
} from '@/state/saleReturnsSlice';
import { useToast } from '@/components/ui/Toast';
import { formatArabicNumber, formatArabicCurrency } from '@/utils/formatArabicNumbers';
import {
  TrendingDown,
  DollarSign,
  ShoppingCart,
  Plus,
  X,
  Search,
  Trash2,
  Edit,
  FileText
} from "lucide-react";

// استخدام أيقونات بسيطة لحل المشكلة
const Clock = ({ className }: { className?: string }) => <span className={className}>⏱️</span>;
const CheckCircle = ({ className }: { className?: string }) => <span className={className}>✓</span>;
const XCircle = ({ className }: { className?: string }) => <span className={className}>✗</span>;

const SaleReturnsPage = () => {
  const { success, error } = useToast();
  const dispatch = useAppDispatch();
  const user = useAppSelector((state) => state.auth.user);
  const currentPage = useAppSelector((state) => state.saleReturns.currentPage);
  const statusFilter = useAppSelector((state) => state.saleReturns.statusFilter);
  const showCreateModal = useAppSelector((state) => state.saleReturns.showCreateModal);
  
  // Local states
  const [selectedReturn, setSelectedReturn] = useState<any>(null);
  const [saleSearchTerm, setSaleSearchTerm] = useState('');
  const [selectedSaleId, setSelectedSaleId] = useState<number | null>(null);
  const [selectedSaleData, setSelectedSaleData] = useState<any>(null);
  const [returnForm, setReturnForm] = useState<CreateSaleReturnRequest>({
    saleId: 0,
    companyId: 0,
    customerId: undefined,
    reason: '',
    notes: '',
    lines: []
  });
  
  // API calls
  const { data: returnsData, isLoading, refetch } = useGetSaleReturnsQuery({
    companyId: user?.isSystemUser ? undefined : user?.companyId,
    status: statusFilter || undefined,
    page: currentPage,
    limit: 10
  });

  const { data: statsData } = useGetSaleReturnStatsQuery({
    companyId: user?.isSystemUser ? undefined : user?.companyId
  });

  const { data: salesData } = useGetSalesQuery({
    page: 1,
    limit: 100,
    search: saleSearchTerm,
    // سنفلتر الفواتير التلقائية في الواجهة الأمامية
  });

  // فلترة الفواتير لإخفاء التلقائية
  const filteredSales = useMemo(() => {
    if (!salesData?.data?.sales) return [];
    return salesData.data.sales.filter(sale => !sale.isAutoGenerated && sale.status === 'APPROVED');
  }, [salesData]);

  const [updateStatus, { isLoading: isUpdating }] = useUpdateReturnStatusMutation();
  const [deleteReturn, { isLoading: isDeleting }] = useDeleteSaleReturnMutation();
  const [createReturn, { isLoading: isCreating }] = useCreateSaleReturnMutation();

  // Handle status update
  const handleStatusUpdate = async (returnId: number, newStatus: ReturnStatus) => {
    try {
      await updateStatus({ returnId, status: newStatus }).unwrap();
      success('تم التحديث بنجاح');
      refetch();
    } catch (err: any) {
      error(err?.data?.message || 'حدث خطأ أثناء تحديث الحالة');
    }
  };

  // Handle delete
  const handleDelete = async (returnId: number) => {
    if (!confirm('هل أنت متأكد من حذف هذا المردود؟')) return;
    
    try {
      await deleteReturn(returnId).unwrap();
      success('تم حذف المردود بنجاح');
      refetch();
    } catch (err: any) {
      error(err?.data?.message || 'حدث خطأ أثناء الحذف');
    }
  };

  // Handle select sale
  const handleSelectSale = async (saleId: number) => {
    setSelectedSaleId(saleId);
    const sale = filteredSales.find((s: any) => s.id === saleId);
    
    if (sale) {
      setSelectedSaleData(sale);
      // Initialize form with sale data
      setReturnForm({
        saleId: sale.id,
        companyId: sale.companyId,
        customerId: sale.customerId,
        reason: '',
        notes: '',
        lines: sale.lines.map((line: any) => ({
          productId: line.productId,
          qty: 0, // المستخدم سيدخل الكمية المردودة
          unitPrice: line.unitPrice,
          maxQty: line.qty, // الحد الأقصى هو كمية الفاتورة الأصلية
          productName: line.product?.name || '',
          isFromParentCompany: line.isFromParentCompany || false,
          parentUnitPrice: line.parentUnitPrice || null,
        }))
      });
    }
  };

  // Handle quantity change for return line
  const handleLineQtyChange = (index: number, qty: number) => {
    setReturnForm(prev => ({
      ...prev,
      lines: prev.lines.map((line, i) => 
        i === index ? { ...line, qty: Math.max(0, Math.min(qty, (line as any).maxQty || 0)) } : line
      )
    }));
  };

  // Handle create return
  const handleCreateReturn = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!returnForm.saleId) {
      error('يجب اختيار فاتورة أولاً');
      return;
    }

    // فلترة الأسطر التي لها كمية أكبر من 0
    const validLines = returnForm.lines.filter((line: any) => line.qty > 0);

    if (validLines.length === 0) {
      error('يجب إدخال كمية مردودة لسطر واحد على الأقل');
      return;
    }

    try {
      await createReturn({
        ...returnForm,
        lines: validLines.map(line => ({
          productId: line.productId,
          qty: line.qty,
          unitPrice: line.unitPrice
        }))
      }).unwrap();
      success('تم إنشاء المردود بنجاح');
      dispatch(setShowCreateModal(false));
      setReturnForm({
        saleId: 0,
        companyId: 0,
        customerId: undefined,
        reason: '',
        notes: '',
        lines: []
      });
      setSelectedSaleId(null);
      setSelectedSaleData(null);
      setSaleSearchTerm('');
      refetch();
    } catch (err: any) {
      error(err?.data?.message || 'حدث خطأ أثناء إنشاء المردود');
    }
  };

  // Get status badge
  const getStatusBadge = (status: ReturnStatus) => {
    const badges = {
      PENDING: {
        label: 'قيد الانتظار',
        color: 'bg-warning-100 text-warning-800',
        icon: <Clock className="w-3 h-3" />
      },
      APPROVED: {
        label: 'معتمد',
        color: 'bg-success-100 text-success-800',
        icon: <CheckCircle className="w-3 h-3" />
      },
      REJECTED: {
        label: 'مرفوض',
        color: 'bg-error-100 text-error-800',
        icon: <XCircle className="w-3 h-3" />
      },
      PROCESSED: {
        label: 'معالج',
        color: 'bg-blue-100 text-blue-800',
        icon: <CheckCircle className="w-3 h-3" />
      }
    };

    const badge = badges[status] || badges.PENDING;
    return (
      <span className={`inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium ${badge.color}`}>
        {badge.icon}
        {badge.label}
      </span>
    );
  };

  return (
    <div className="p-6 max-w-7xl mx-auto bg-background-secondary min-h-screen" dir="rtl">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-3">
            <TrendingDown className="w-8 h-8 text-primary-600" />
            <div>
              <h1 className="text-3xl font-bold text-text-primary">مردودات المبيعات</h1>
              <p className="text-text-secondary">إدارة وتتبع مردودات المنتجات والمبالغ المستردة</p>
            </div>
          </div>
          <button
            onClick={() => dispatch(setShowCreateModal(true))}
            className="flex items-center gap-2 bg-primary-600 text-white px-4 py-2 rounded-lg hover:bg-primary-700 transition-all duration-200 shadow-md hover:shadow-lg"
          >
            <Plus className="w-5 h-5" />
            إنشاء مردود جديد
          </button>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        {/* Total Returns */}
        <div className="bg-surface-primary p-4 rounded-lg shadow-sm border border-border-primary hover:shadow-md transition-shadow duration-200">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-text-secondary mb-1">إجمالي المردودات</p>
              <p className="text-2xl font-bold text-text-primary">
                {formatArabicNumber(statsData?.data?.totalReturns || 0)}
              </p>
            </div>
            <div className="w-12 h-12 bg-gradient-to-br from-primary-500 to-primary-600 rounded-xl flex items-center justify-center shadow-md">
              <ShoppingCart className="w-6 h-6 text-white" />
            </div>
          </div>
        </div>

        {/* Pending */}
        <div className="bg-surface-primary p-4 rounded-lg shadow-sm border border-border-primary hover:shadow-md transition-shadow duration-200">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-text-secondary mb-1">قيد الانتظار</p>
              <p className="text-2xl font-bold text-text-primary">
                {formatArabicNumber(statsData?.data?.pendingReturns || 0)}
              </p>
            </div>
            <div className="w-12 h-12 bg-gradient-to-br from-warning-500 to-warning-600 rounded-xl flex items-center justify-center shadow-md">
              <Clock className="w-6 h-6 text-white" />
            </div>
          </div>
        </div>

        {/* Total Amount */}
        <div className="bg-surface-primary p-4 rounded-lg shadow-sm border border-border-primary hover:shadow-md transition-shadow duration-200">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-text-secondary mb-1">المبلغ الإجمالي</p>
              <p className="text-2xl font-bold text-text-primary">
                {formatArabicCurrency(statsData?.data?.totalAmount || 0)}
              </p>
            </div>
            <div className="w-12 h-12 bg-gradient-to-br from-success-500 to-success-600 rounded-xl flex items-center justify-center shadow-md">
              <DollarSign className="w-6 h-6 text-white" />
            </div>
          </div>
        </div>
      </div>

      {/* Filters */}
      <div className="bg-surface-primary p-4 rounded-lg shadow-sm border border-border-primary mb-6">
        <div className="flex flex-wrap gap-3">
          <button
            onClick={() => dispatch(setStatusFilter(''))}
            className={`px-4 py-2 rounded-lg font-medium transition-all duration-200 ${
              !statusFilter
                ? 'bg-primary-600 text-white shadow-md'
                : 'bg-background-secondary text-text-secondary hover:bg-background-hover'
            }`}
          >
            الكل ({formatArabicNumber(statsData?.data?.totalReturns || 0)})
          </button>
          <button
            onClick={() => dispatch(setStatusFilter('PENDING'))}
            className={`px-4 py-2 rounded-lg font-medium transition-all duration-200 flex items-center gap-2 ${
              statusFilter === 'PENDING'
                ? 'bg-warning-600 text-white shadow-md'
                : 'bg-background-secondary text-text-secondary hover:bg-background-hover'
            }`}
          >
            <Clock className="w-4 h-4" />
            قيد الانتظار ({formatArabicNumber(statsData?.data?.pendingReturns || 0)})
          </button>
          <button
            onClick={() => dispatch(setStatusFilter('APPROVED'))}
            className={`px-4 py-2 rounded-lg font-medium transition-all duration-200 flex items-center gap-2 ${
              statusFilter === 'APPROVED'
                ? 'bg-success-600 text-white shadow-md'
                : 'bg-background-secondary text-text-secondary hover:bg-background-hover'
            }`}
          >
            <CheckCircle className="w-4 h-4" />
            معتمد ({formatArabicNumber(statsData?.data?.approvedReturns || 0)})
          </button>
          <button
            onClick={() => dispatch(setStatusFilter('REJECTED'))}
            className={`px-4 py-2 rounded-lg font-medium transition-all duration-200 flex items-center gap-2 ${
              statusFilter === 'REJECTED'
                ? 'bg-error-600 text-white shadow-md'
                : 'bg-background-secondary text-text-secondary hover:bg-background-hover'
            }`}
          >
            <XCircle className="w-4 h-4" />
            مرفوض
          </button>
        </div>
      </div>

      {/* Returns Table */}
      <div className="bg-surface-primary rounded-lg shadow-sm border border-border-primary overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-border-primary">
            <thead className="bg-background-secondary">
              <tr>
                <th className="px-6 py-3 text-right text-xs font-medium text-text-secondary uppercase tracking-wider">
                  رقم المردود
                </th>
                <th className="px-6 py-3 text-right text-xs font-medium text-text-secondary uppercase tracking-wider">
                  رقم الفاتورة
                </th>
                <th className="px-6 py-3 text-right text-xs font-medium text-text-secondary uppercase tracking-wider">
                  العميل
                </th>
                <th className="px-6 py-3 text-right text-xs font-medium text-text-secondary uppercase tracking-wider">
                  المبلغ
                </th>
                <th className="px-6 py-3 text-right text-xs font-medium text-text-secondary uppercase tracking-wider">
                  السبب
                </th>
                <th className="px-6 py-3 text-right text-xs font-medium text-text-secondary uppercase tracking-wider">
                  الحالة
                </th>
                <th className="px-6 py-3 text-right text-xs font-medium text-text-secondary uppercase tracking-wider">
                  التاريخ
                </th>
                <th className="px-6 py-3 text-right text-xs font-medium text-text-secondary uppercase tracking-wider">
                  الإجراءات
                </th>
              </tr>
            </thead>
            <tbody className="bg-surface-primary divide-y divide-border-primary">
              {isLoading ? (
                <tr>
                  <td colSpan={8} className="px-6 py-12 text-center text-text-secondary">
                    <div className="flex flex-col items-center gap-3">
                      <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600"></div>
                      <p>جاري التحميل...</p>
                    </div>
                  </td>
                </tr>
              ) : returnsData?.data?.length === 0 ? (
                <tr>
                  <td colSpan={8} className="px-6 py-12 text-center text-text-secondary">
                    <div className="flex flex-col items-center gap-3">
                      <TrendingDown className="w-12 h-12 text-text-tertiary" />
                      <div>
                        <p className="text-lg font-medium mb-1">لا توجد مردودات</p>
                        <p className="text-sm">ابدأ بإنشاء أول مردود</p>
                      </div>
                    </div>
                  </td>
                </tr>
              ) : (
                returnsData?.data?.map((returnItem: any) => (
                  <tr key={returnItem.id} className="hover:bg-background-hover transition-colors duration-150">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="text-sm font-medium text-text-primary">
                        #{formatArabicNumber(returnItem.id)}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="text-sm text-text-primary">
                        {returnItem.sale?.invoiceNumber || `#${returnItem.saleId}`}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="text-sm text-text-primary">
                        {returnItem.customer?.name || '-'}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="text-sm font-medium text-success-600">
                        {formatArabicCurrency(returnItem.total)}
                      </span>
                    </td>
                    <td className="px-6 py-4">
                      <span className="text-sm text-text-secondary line-clamp-1">
                        {returnItem.reason || '-'}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      {getStatusBadge(returnItem.status)}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-text-secondary">
                      {new Date(returnItem.createdAt).toLocaleDateString('ar-LY')}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                      <div className="flex items-center gap-2">
                        {returnItem.status === 'PENDING' && (
                          <>
                            <button
                              onClick={() => handleStatusUpdate(returnItem.id, 'APPROVED')}
                              className="text-success-600 hover:text-success-900 p-1.5 rounded-md hover:bg-success-50 transition-colors"
                              title="اعتماد"
                            >
                              <CheckCircle className="w-4 h-4" />
                            </button>
                            <button
                              onClick={() => handleStatusUpdate(returnItem.id, 'REJECTED')}
                              className="text-error-600 hover:text-error-900 p-1.5 rounded-md hover:bg-error-50 transition-colors"
                              title="رفض"
                            >
                              <XCircle className="w-4 h-4" />
                            </button>
                          </>
                        )}
                        <button
                          onClick={() => handleDelete(returnItem.id)}
                          className="text-error-600 hover:text-error-900 p-1.5 rounded-md hover:bg-error-50 transition-colors"
                          title="حذف"
                          disabled={isDeleting}
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        {returnsData?.pagination && returnsData.pagination.totalPages > 1 && (
          <div className="bg-surface-primary px-4 py-3 flex items-center justify-between border-t border-border-primary sm:px-6">
            <div className="flex-1 flex justify-between sm:hidden">
              <button
                onClick={() => dispatch(setCurrentPage(Math.max(1, currentPage - 1)))}
                disabled={currentPage === 1}
                className="relative inline-flex items-center px-4 py-2 border border-border-primary text-sm font-medium rounded-md text-text-primary bg-surface-primary hover:bg-background-hover disabled:opacity-50"
              >
                السابق
              </button>
              <span className="text-sm text-text-secondary">
                {formatArabicNumber(currentPage)} / {formatArabicNumber(returnsData.pagination.totalPages)}
              </span>
              <button
                onClick={() => dispatch(setCurrentPage(Math.min(returnsData.pagination.totalPages, currentPage + 1)))}
                disabled={currentPage === returnsData.pagination.totalPages}
                className="relative inline-flex items-center px-4 py-2 border border-border-primary text-sm font-medium rounded-md text-text-primary bg-surface-primary hover:bg-background-hover disabled:opacity-50"
              >
                التالي
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Create Return Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4">
          <div className="bg-surface-primary rounded-lg shadow-xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
            {/* Modal Header */}
            <div className="sticky top-0 bg-gradient-to-r from-primary-600 to-primary-700 text-white px-6 py-4 flex justify-between items-center rounded-t-lg">
              <div className="flex items-center gap-3">
                <TrendingDown className="w-6 h-6" />
                <h2 className="text-xl font-bold">إنشاء مردود جديد</h2>
              </div>
              <button 
                onClick={() => {
                  dispatch(setShowCreateModal(false));
                  setSelectedSaleId(null);
                  setSelectedSaleData(null);
                  setSaleSearchTerm('');
                }} 
                className="text-white hover:text-gray-200 transition-colors"
              >
                <X className="w-6 h-6" />
              </button>
            </div>

            <form onSubmit={handleCreateReturn} className="p-6">
              {/* Step 1: Select Sale */}
              {!selectedSaleId && (
                <div className="mb-6">
                  <h3 className="text-lg font-semibold text-text-primary mb-4 flex items-center gap-2">
                    <FileText className="w-5 h-5 text-primary-600" />
                    الخطوة 1: اختر الفاتورة
                  </h3>
                  
                  {/* Search */}
                  <div className="relative mb-4">
                    <Search className="absolute right-3 top-1/2 transform -translate-y-1/2 text-text-tertiary w-5 h-5" />
                    <input
                      type="text"
                      placeholder="ابحث برقم الفاتورة أو اسم العميل..."
                      value={saleSearchTerm}
                      onChange={(e) => setSaleSearchTerm(e.target.value)}
                      className="w-full pr-10 pl-4 py-2.5 border border-border-primary rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-primary-500 bg-background-secondary text-text-primary placeholder-text-muted"
                    />
                  </div>

                  {/* Sales List */}
                  <div className="max-h-96 overflow-y-auto border border-border-primary rounded-lg">
                    {filteredSales.length === 0 ? (
                      <div className="p-8 text-center text-text-secondary">
                        <ShoppingCart className="w-12 h-12 mx-auto mb-3 text-text-tertiary" />
                        <p>لا توجد فواتير متاحة للإرجاع</p>
                        <p className="text-sm mt-1">يجب أن تكون الفاتورة معتمدة</p>
                      </div>
                    ) : (
                      filteredSales.map((sale: any) => (
                        <button
                          key={sale.id}
                          type="button"
                          onClick={() => handleSelectSale(sale.id)}
                          className="w-full p-4 border-b border-border-primary hover:bg-background-hover transition-colors text-right"
                        >
                          <div className="flex items-center justify-between">
                            <div>
                              <p className="font-medium text-text-primary">
                                {sale.invoiceNumber || `#${sale.id}`}
                              </p>
                              <p className="text-sm text-text-secondary mt-1">
                                {sale.customer?.name || 'عميل نقدي'} • {formatArabicCurrency(sale.total)}
                              </p>
                            </div>
                            <div className="text-xs text-text-tertiary">
                              {new Date(sale.createdAt).toLocaleDateString('ar-LY')}
                            </div>
                          </div>
                        </button>
                      ))
                    )}
                  </div>
                </div>
              )}

              {/* Step 2: Enter Return Details */}
              {selectedSaleId && selectedSaleData && (
                <div>
                  <div className="mb-4 p-4 bg-primary-50 border border-primary-200 rounded-lg">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-sm text-text-secondary">الفاتورة المختارة:</p>
                        <p className="font-bold text-text-primary">
                          {selectedSaleData.invoiceNumber || `#${selectedSaleData.id}`}
                        </p>
                      </div>
                      <button
                        type="button"
                        onClick={() => {
                          setSelectedSaleId(null);
                          setSelectedSaleData(null);
                        }}
                        className="text-primary-600 hover:text-primary-800 text-sm underline"
                      >
                        تغيير الفاتورة
                      </button>
                    </div>
                  </div>

                  <h3 className="text-lg font-semibold text-text-primary mb-4">
                    الخطوة 2: حدد الأصناف والكميات المردودة
                  </h3>

                  {/* Return Lines */}
                  <div className="space-y-3 mb-6 max-h-64 overflow-y-auto">
                    {returnForm.lines.map((line: any, index) => (
                      <div key={index} className="p-4 bg-background-secondary border border-border-primary rounded-lg">
                        <div className="flex items-center justify-between gap-4">
                          <div className="flex-1">
                            <p className="font-medium text-text-primary">{line.productName}</p>
                            <p className="text-sm text-text-secondary mt-1">
                              السعر: {formatArabicCurrency(line.unitPrice)} • 
                              الكمية الأصلية: {formatArabicNumber(line.maxQty)}
                              {line.isFromParentCompany && (
                                <span className="mr-2 text-warning-600">• من التقازي</span>
                              )}
                            </p>
                          </div>
                          <div className="flex items-center gap-3">
                            <div className="w-32">
                              <label className="block text-xs text-text-secondary mb-1">الكمية المردودة</label>
                              <input
                                type="number"
                                min="0"
                                max={line.maxQty}
                                step="0.01"
                                value={line.qty}
                                onChange={(e) => handleLineQtyChange(index, parseFloat(e.target.value) || 0)}
                                className="w-full px-3 py-2 border border-border-primary rounded-md focus:ring-2 focus:ring-primary-500 focus:border-primary-500 bg-surface-primary text-text-primary"
                              />
                            </div>
                            <div className="w-32">
                              <label className="block text-xs text-text-secondary mb-1">المجموع الفرعي</label>
                              <div className="px-3 py-2 bg-surface-primary border border-border-primary rounded-md">
                                <span className="font-semibold text-primary-600">
                                  {formatArabicCurrency(line.qty * line.unitPrice)}
                                </span>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>

                  {/* Return Details */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                    <div>
                      <label className="block text-sm font-medium text-text-primary mb-2">
                        سبب الإرجاع *
                      </label>
                      <select
                        required
                        value={returnForm.reason}
                        onChange={(e) => setReturnForm(prev => ({ ...prev, reason: e.target.value }))}
                        className="w-full px-3 py-2 border border-border-primary rounded-md focus:ring-2 focus:ring-primary-500 focus:border-primary-500 bg-surface-primary text-text-primary"
                      >
                        <option value="">اختر السبب</option>
                        <option value="بضاعة زائدة">بضاعة زائدة</option>
                        <option value="عيب في المنتج">عيب في المنتج</option>
                        <option value="منتج غير مطابق">منتج غير مطابق</option>
                        <option value="تالف">تالف</option>
                        <option value="غير راضي">غير راضي</option>
                        <option value="أخرى">أخرى</option>
                      </select>
                    </div>

                  </div>

                  <div className="mb-6">
                    <label className="block text-sm font-medium text-text-primary mb-2">
                      ملاحظات إضافية
                    </label>
                    <textarea
                      value={returnForm.notes}
                      onChange={(e) => setReturnForm(prev => ({ ...prev, notes: e.target.value }))}
                      rows={3}
                      className="w-full px-3 py-2 border border-border-primary rounded-md focus:ring-2 focus:ring-primary-500 focus:border-primary-500 bg-surface-primary text-text-primary"
                      placeholder="أدخل أي ملاحظات إضافية..."
                    />
                  </div>

                  {/* Total Summary */}
                  {selectedSaleId && (
                    <div className="bg-primary-50 border border-primary-200 rounded-lg p-4 mb-6">
                      <div className="flex justify-between items-center">
                        <span className="text-lg font-semibold text-text-primary">المبلغ الإجمالي للمردود:</span>
                        <span className="text-2xl font-bold text-primary-600">
                          {formatArabicCurrency(
                            returnForm.lines.reduce((sum: number, line: any) => 
                              sum + (line.qty * line.unitPrice), 0
                            )
                          )}
                        </span>
                      </div>
                    </div>
                  )}
                </div>
              )}

              {/* Actions */}
              <div className="flex justify-end gap-3 pt-4 border-t border-border-primary">
                <button
                  type="button"
                  onClick={() => {
                    dispatch(setShowCreateModal(false));
                    setSelectedSaleId(null);
                    setSelectedSaleData(null);
                    setSaleSearchTerm('');
                  }}
                  className="px-4 py-2 bg-background-secondary text-text-primary rounded-lg hover:bg-background-hover border border-border-primary transition-colors"
                >
                  إلغاء
                </button>
                {selectedSaleId && (
                  <button
                    type="submit"
                    disabled={isCreating}
                    className="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center gap-2"
                  >
                    {isCreating ? (
                      <>
                        <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                        جاري الإنشاء...
                      </>
                    ) : (
                      <>
                        <CheckCircle className="w-4 h-4" />
                        إنشاء المردود
                      </>
                    )}
                  </button>
                )}
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default SaleReturnsPage;
